# Generated by Django 5.1.6 on 2025-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
