# Generated by Django 5.1.6 on 2025-04-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tag_customuser_chest_bust_customuser_foot_size_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='product_type_tags',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fashion_tags',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
