# Generated by Django 5.1.6 on 2025-04-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_product_type_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
