# Generated by Django 5.1.6 on 2025-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_setup_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('buyer', 'product')},
        ),
    ]
